import numpy as np
# built-in numpy functions include np.sum, np.prod,np.mean, np.std, np.var, np.min, np.max, np.argmin,np.argmax,np.sort
a=np.zeros(3)
print(a)
print(a.shape)
z=np.ones(10)
print(z)
b=np.linspace(2,20,10)
print(b)
type(b[1])
c=np.random.randint(0,9, size=8)
d=np.std(c)
e=np.var(c)
f=np.mean(c)
print(" For a randomly generated array {} , we get a mean of {:.2f} and a varation of {:.2f} and standard deviation of {:.2f}.".format(c,f,e,d))
print(c[c>4])
F=np.where(c< 1,1,c) #replaces any element of C with value less than 1 (in other words i where c[i]=0) with 1 and all other elements witth original value (c[i])
print(F)
print(c)
print(c+F)
print(5*F)
print(np.sort(c*F))
g=np.random.randint(0,9,size=10)

c=list(enumerate([5,4,2]))
print(c[0][0])